// Event rows are derived from content/site.config.json (DATA-01): the same object the static site
// is built from. `normaliseEvents` is shared by the owner-only PUT /admin/events endpoint and by
// scripts/events-sync.mjs, which prints SQL for `wrangler d1 execute`.

import { HttpError } from './http.js';

export function normaliseEvents(config) {
  const timezone = config && config.wedding && config.wedding.timezone;
  const events = config && Array.isArray(config.events) ? config.events : null;
  if (!timezone || !events || !events.length) throw new HttpError(400, 'validation', 'Expected { wedding: { timezone }, events: [...] } as in content/site.config.json.');
  const mc = config.rsvp && config.rsvp.mealChoices;
  let mealEventId = null;
  let mealOptions = null;
  if (mc && (mc.eventId || (Array.isArray(mc.options) && mc.options.length))) {
    if (typeof mc.eventId !== 'string' || !events.some((e) => e && e.id === mc.eventId)) throw new HttpError(400, 'validation', 'rsvp.mealChoices.eventId must name one of the events.');
    if (!Array.isArray(mc.options) || mc.options.length < 2 || mc.options.some((o) => typeof o !== 'string' || !o.trim())) throw new HttpError(400, 'validation', 'rsvp.mealChoices.options needs at least two non-empty strings.');
    mealEventId = mc.eventId;
    mealOptions = mc.options.map((o) => o.trim());
  }
  return events.map((ev, i) => {
    if (!ev || typeof ev.id !== 'string' || !/^[a-z0-9-]{1,32}$/.test(ev.id)) throw new HttpError(400, 'validation', `events[${i}].id is invalid.`);
    if (typeof ev.startsAt !== 'string' || !Number.isFinite(Date.parse(ev.startsAt))) throw new HttpError(400, 'validation', `events[${i}].startsAt must be ISO 8601 with an offset.`);
    if (ev.endsAt !== null && ev.endsAt !== undefined && !Number.isFinite(Date.parse(ev.endsAt))) throw new HttpError(400, 'validation', `events[${i}].endsAt must be ISO 8601 or null.`);
    const venue = ev.venue || {};
    return {
      id: ev.id,
      label: String(ev.label || ev.id),
      name: String(ev.name || venue.name || ev.id),
      venueName: String(venue.name || ev.name || ''),
      startsAtUtc: new Date(Date.parse(ev.startsAt)).toISOString(),
      startsAtLocal: ev.startsAt,
      endsAtUtc: ev.endsAt ? new Date(Date.parse(ev.endsAt)).toISOString() : null,
      timezone,
      directionsConfirmed: !!(venue.entrance || venue.arrival),
      approvalState: (ev.approval && ev.approval.state) || 'pending',
      sortOrder: i,
      mealOptions: ev.id === mealEventId ? mealOptions : null,
    };
  });
}

export const UPSERT_EVENT_SQL = `INSERT INTO event (id, label, name, venue_name, starts_at_utc, starts_at_local, ends_at_utc, timezone, directions_confirmed, approval_state, sort_order, meal_options_json, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET label = excluded.label, name = excluded.name, venue_name = excluded.venue_name, starts_at_utc = excluded.starts_at_utc,
  starts_at_local = excluded.starts_at_local, ends_at_utc = excluded.ends_at_utc, timezone = excluded.timezone, directions_confirmed = excluded.directions_confirmed,
  approval_state = excluded.approval_state, sort_order = excluded.sort_order, meal_options_json = excluded.meal_options_json, updated_at = excluded.updated_at`;

export function eventParams(ev, now) {
  return [ev.id, ev.label, ev.name, ev.venueName, ev.startsAtUtc, ev.startsAtLocal, ev.endsAtUtc, ev.timezone, ev.directionsConfirmed ? 1 : 0, ev.approvalState, ev.sortOrder, ev.mealOptions ? JSON.stringify(ev.mealOptions) : null, now];
}

// Parses the stored option list; returns null when meals are not collected for the event.
export function mealOptionsOf(row) {
  if (!row || !row.meal_options_json) return null;
  try {
    const parsed = JSON.parse(row.meal_options_json);
    return Array.isArray(parsed) && parsed.length ? parsed : null;
  } catch {
    return null;
  }
}

function sqlString(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}

export function eventsToSql(config, now = new Date().toISOString()) {
  const events = normaliseEvents(config);
  const lines = ['-- Generated by backend/scripts/events-sync.mjs from content/site.config.json. Do not edit by hand.'];
  for (const ev of events) {
    const params = eventParams(ev, now);
    let i = 0;
    lines.push(`${UPSERT_EVENT_SQL.replace(/\?/g, () => sqlString(params[i++]))};`);
  }
  return `${lines.join('\n')}\n`;
}
